site_name: pyKMC
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: orange
  features:
  - content.code.copy  # Ajoute un bouton "Copier" sur les blocs de code
  - content.code.annotate  # Active le surlignage de syntaxe
  - content.code.highlight  # Améliore le rendu du code

nav:
  - Home: index.md
  - Getting Started:
      - Installation: install/installation.md
  - User Guide : user_guide.md
  - Troubleshooting: troubleshooting.md
  - KMC Parameters : parameters.md
  - Tutorial: 
      - pyKMC Workflow : 0-pyKMC-workflow.md 
      - Simple example : 1-pyKMC-simple.md
  - API Reference: 
      - System: api/system.md
      - NeighborsList: api/neighbors_list.md
      - AtomicEnvironment: api/atomic_environment.md
      - Config: api/config.md
      - Log: api/log.md
      - Algorithms: api/algorithms.md
      - KMC: api/kmc.md 
      - Environments: api/environments.md
      - Engine: api/engine.md
      - LammpsEngine: api/lammpsengine.md
      - EventTable : api/event_table.md
      - EventSearch : api/eventsearch.md
      - Refinement : api/refinement.md
      - PointSetRegistration : api/point_set_registration.md
      - Symmetries : api/symmetries.md
      - RateConstante : api/rate_constant.md
      - Initialize : api/initializer.md
      - Result : api/result.md
      - Info: api/info_simulations.md
      - Utils: api/utils.md
      - run : api/run.md

markdown_extensions:
  - pymdownx.arithmatex:
  - mdx_include:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            heading_level: 2
            members_order: alphabetical
            separate_signature: true
            show_docstring_examples: true
            show_root_heading: true
  - search:
  - mkdocs-jupyter:
use_directory_urls: false
site_url: https://hugomoison.github.io/pyKMC/
